version: "3.8"
services:
  mysql:
    image: "mysql:latest"
    container_name: mysql-devbyul
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devbyul
      - MYSQL_USER=devbyul
      - MYSQL_PASSWORD=devbyul
    ports: 
      - "13306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d